name: Test the backend with unit tests

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install all the dependencies needed
        working-directory: backend
        run: pip install -r requirements.pip

      - name: Run unit tests
        working-directory: backend
        run: pytest -m unit --no-cov
